name = "meraki-exporter-docs"
compatibility_date = "2025-04-01"
routes = [
  { pattern = "meraki.exporters.m7kni.com", custom_domain = true }
]

[assets]
directory = "./site"
not_found_handling = "404-page"

[observability.logs]
enabled = true
